apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::913524915763:user/kuldevops
      username: kuldevops
      groups:
        - system:masters
