apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rbac
  namespace: monitoring
subjects:
  - kind: User
    name: admin # This refers to your Kubernetes user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin # This is the built-in admin role in the monitoring namespace
  apiGroup: rbac.authorization.k8s.io
